#!/bin/bash

### This script is called before the user change environment variables in application setting page.

echo "========== [reader] config_init start =========="
env | grep '^TRIM_' | sort
echo "==================================================="
exit 0
