#!/bin/bash

### This script is called before the user installs the application.

echo "========== [reader] install_init start =========="
env | grep '^TRIM_' | sort
echo "==================================================="

exit 0
