#!/bin/bash

### This script is called before the user uninstalls the application.

echo "========== [reader] uninstall_init start =========="
env | grep '^TRIM_' | sort
echo "==================================================="

exit 0
