import antfu from '@antfu/eslint-config'

export default antfu(
  {
    stylistic: false,
    typescript: true,
    vue: true,
    react: true,
    formatters: false,
    jsonc: false,
    yaml: false,
    ignores: [
      '**/lib/**',
      '**/dist/**',
      '**/.turbo/**',
      '**/coverage/**',
      'apps/**/app/**',
      'apps/**/cmd/**',
      'apps/**/wizard/**',
      'packages/fnos-gateway/src/client/bridge.ts',
      'scripts/validate-json.ts',
    ],
  },
  {
    rules: {
      'antfu/if-newline': 'off',
      'antfu/no-top-level-await': 'off',
      'antfu/consistent-list-newline': 'off',
      'import/consistent-type-specifier-style': 'off',
      'import/first': 'off',
      'import/no-duplicates': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-exports': 'off',
      'perfectionist/sort-named-exports': 'off',
      'node/prefer-global/buffer': 'off',
      'node/prefer-global/process': 'off',
      'prefer-template': 'off',
      'regexp/no-super-linear-backtracking': 'off',
      'regexp/no-useless-non-capturing-group': 'off',
      'regexp/optimal-quantifier-concatenation': 'off',
      'regexp/no-misleading-capturing-group': 'off',
      'regexp/use-ignore-case': 'off',
      'regexp/prefer-w': 'off',
      'ts/consistent-type-definitions': 'off',
      'ts/method-signature-style': 'off',
      'ts/no-import-type-side-effects': 'off',
      'ts/no-use-before-define': 'off',
      'style/brace-style': 'off',
      'style/max-statements-per-line': 'off',
      'style/operator-linebreak': 'off',
      'style/jsx-one-expression-per-line': 'off',
      'style/jsx-curly-brace-presence': 'off',
      'style/member-delimiter-style': 'off',
      'style/quote-props': 'off',
      'test/prefer-lowercase-title': 'off',
      'no-console': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    files: ['plugins/**/*.ts', 'plugins/**/*.tsx'],
    rules: {
      'no-console': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    files: ['docs/**/*.ts', 'docs/**/*.mts', 'docs/**/*.vue'],
    rules: {
      'no-console': 'off',
    },
  },
)
