/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const -: typeof import('from')['-']
  const B: typeof import('name').B
  const E: typeof import('name').E
  const M: typeof import('name').M
  const a: typeof import('name').a
  const e: typeof import('name').e
  const g: typeof import('name').g
  const l: typeof import('name').l
  const m: typeof import('from').m
  const n: typeof import('from').n
  const o: typeof import('name').o
  const p: typeof import('from').p
  const s: typeof import('name').s
  const t: typeof import('from').t
  const u: typeof import('from').u
  const x: typeof import('name').x
}
