/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BackupCard: typeof import('./src/components/BackupCard.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LogCard: typeof import('./src/components/LogCard.vue')['default']
    PasswordCard: typeof import('./src/components/PasswordCard.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    UpdateCard: typeof import('./src/components/UpdateCard.vue')['default']
  }
}
