/** Same-origin Web routes for the standalone Codex OAuth flow. */

import type { IncomingMessage, ServerResponse } from 'node:http'
import type { Context } from '@deepseek-ai/cordis'
import type {} from '@deepseek-ai/dsh-host-webserver'
import type { AuthEvent, AuthPrompt } from '@earendil-works/pi-ai'
import { codexAuthStatus, loginCodex, logoutCodex } from './auth.ts'
import type { CodexCredentialMirror } from './credential-mirror.ts'
import type { CodexCredentialStore } from './store.ts'
import {
  CODEX_AUTH_LOGIN_PATH,
  CODEX_AUTH_LOGOUT_PATH,
  CODEX_AUTH_SETTINGS_PATH,
  CODEX_AUTH_STATUS_PATH,
  CODEX_USAGE_PATH,
} from './auth-paths.ts'
import { CodexUsageService } from './usage.ts'
import type { SettingsScope } from '@deepseek-ai/dsh-settings'
import { decodeCodexAuthSettings } from './settings-contract.ts'
import type { CodexAuthSettingsConfig } from './settings-contract.ts'

export const CODEX_AUTH_URL_TIMEOUT_MS = 30_000
export const REMOTE_WEB_ORIGIN_NOT_TRUSTED = 'remote-web-origin-not-trusted'
export const CODEX_USAGE_UNAVAILABLE = 'codex-usage-unavailable'
export const CODEX_SETTINGS_INVALID = 'codex-settings-invalid'

const CODEX_SETTINGS_BODY_LIMIT = 8 * 1024

export type CodexWebAuthStatus =
  | { status: 'signed-out' }
  | { status: 'signing-in' }
  | { status: 'signed-in'; expiresAt?: Date }
  | { status: 'error'; message: string }

/** One-time code generated by the Codex device authorization flow. */
export interface CodexLoginChallenge {
  type: 'device_code'
  userCode: string
  verificationUri: string
  intervalSeconds?: number
  expiresInSeconds?: number
}

function signedInStatus(expiresAt: Date | undefined): CodexWebAuthStatus {
  return expiresAt === undefined
    ? { status: 'signed-in' }
    : { status: 'signed-in', expiresAt }
}

function safeMessage(error: unknown): string {
  return (error instanceof Error ? error.message : String(error))
    .replace(/\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\b/gu, '[redacted token]')
    .replace(/(\b(?:code|token|refresh_token|access_token)=)[^&\s]+/giu, '$1[redacted]')
    .slice(0, 1000)
}

function waitForPromptAbort(prompt: AuthPrompt): Promise<string> {
  const signal = prompt.signal
  if (signal === undefined) return new Promise<string>(() => {})
  if (signal.aborted) return Promise.reject(signal.reason)
  return new Promise<string>((_resolve, reject) => {
    signal.addEventListener('abort', () => { reject(signal.reason) }, { once: true })
  })
}

/** Owns one device-code login operation and prevents duplicate auth requests. */
export class CodexWebAuth {
  private state: CodexWebAuthStatus = { status: 'signed-out' }
  private operation: Promise<void> | undefined
  private cancellation: AbortController | undefined
  private challenge: CodexLoginChallenge | undefined
  private challengeWaiters: Array<{ resolve(value: CodexLoginChallenge): void; reject(error: unknown): void }> = []
  private challengeTimer: ReturnType<typeof setTimeout> | undefined

  constructor(
    private readonly store: CodexCredentialStore,
    private readonly challengeTimeoutMs = CODEX_AUTH_URL_TIMEOUT_MS,
    private readonly mirror?: CodexCredentialMirror,
  ) {
    if (!Number.isFinite(challengeTimeoutMs) || challengeTimeoutMs <= 0) {
      throw new TypeError('Codex auth URL timeout must be a positive finite number')
    }
  }

  async status(): Promise<CodexWebAuthStatus> {
    if (this.operation !== undefined) return this.state
    if (this.state.status === 'error') return this.state
    const stored = await codexAuthStatus(this.store)
    if (stored.authenticated) {
      await this.mirror?.sync()
      return signedInStatus(stored.expiresAt)
    }
    await this.mirror?.clear()
    return { status: 'signed-out' }
  }

  async signIn(): Promise<CodexLoginChallenge> {
    if (this.operation === undefined) this.start()
    if (this.challenge !== undefined) return this.challenge
    return new Promise<CodexLoginChallenge>((resolve, reject) => {
      this.challengeWaiters.push({ resolve, reject })
    })
  }

  async signOut(): Promise<void> {
    this.cancelSignIn(new Error('Codex sign-in cancelled'))
    await this.operation?.catch(() => undefined)
    await logoutCodex(this.store)
    await this.mirror?.clear()
    this.challenge = undefined
    this.state = { status: 'signed-out' }
  }

  async dispose(): Promise<void> {
    this.cancelSignIn(new Error('Codex auth plugin disposed'))
    await this.operation?.catch(() => undefined)
  }

  private start(): void {
    const cancellation = new AbortController()
    this.cancellation = cancellation
    this.challenge = undefined
    this.state = { status: 'signing-in' }
    this.challengeTimer = setTimeout(() => {
      this.cancelSignIn(new Error(`Codex did not provide an authorization code within ${String(this.challengeTimeoutMs)}ms`))
    }, this.challengeTimeoutMs)
    this.challengeTimer.unref()
    this.operation = loginCodex({
      signal: cancellation.signal,
      prompt: prompt => {
        // The Web card owns the device-code UX. Codex OAuth has no workspace
        // selection step; the only select prompt is the browser/device method.
        if (prompt.type === 'select') return Promise.resolve('device_code')
        return waitForPromptAbort(prompt)
      },
      notify: event => { this.onEvent(event) },
    }, this.store).then(
      async () => {
        if (this.challenge === undefined) {
          const error = new Error('Codex sign-in finished without an authorization code')
          this.rejectChallenge(error)
          this.state = { status: 'error', message: safeMessage(error) }
          return
        }
        const stored = await codexAuthStatus(this.store)
        if (stored.authenticated) await this.mirror?.sync()
        this.state = stored.authenticated ? signedInStatus(stored.expiresAt) : { status: 'signed-out' }
      },
      (error: unknown) => {
        this.rejectChallenge(error)
        this.state = { status: 'error', message: safeMessage(error) }
      },
    ).finally(() => {
      this.clearChallengeTimer()
      this.operation = undefined
      this.cancellation = undefined
    })
  }

  private onEvent(event: AuthEvent): void {
    if (event.type !== 'device_code') return
    let url: URL
    try {
      url = new URL(event.verificationUri)
    } catch {
      this.cancelSignIn(new Error('OpenAI returned an invalid Codex authorization URL'))
      return
    }
    if (url.protocol !== 'https:' || url.username !== '' || url.password !== '') {
      this.cancelSignIn(new Error('OpenAI returned an unsafe Codex authorization URL'))
      return
    }
    if (event.userCode.trim().length === 0) {
      this.cancelSignIn(new Error('OpenAI returned an empty Codex authorization code'))
      return
    }
    this.challenge = {
      type: 'device_code',
      userCode: event.userCode,
      verificationUri: event.verificationUri,
      ...(event.intervalSeconds === undefined ? {} : { intervalSeconds: event.intervalSeconds }),
      ...(event.expiresInSeconds === undefined ? {} : { expiresInSeconds: event.expiresInSeconds }),
    }
    this.clearChallengeTimer()
    for (const waiter of this.challengeWaiters.splice(0)) waiter.resolve(this.challenge)
  }

  private rejectChallenge(error: unknown): void {
    this.clearChallengeTimer()
    for (const waiter of this.challengeWaiters.splice(0)) waiter.reject(error)
  }

  private clearChallengeTimer(): void {
    if (this.challengeTimer === undefined) return
    clearTimeout(this.challengeTimer)
    this.challengeTimer = undefined
  }

  private cancelSignIn(error: Error): void {
    this.rejectChallenge(error)
    this.cancellation?.abort(error)
  }
}

function header(req: IncomingMessage, name: string): string | undefined {
  const value = req.headers[name]
  return Array.isArray(value) ? value[0] : value
}

function firstForwarded(value: string | undefined): string | undefined {
  return value?.split(',')[0]?.trim() || undefined
}

function requestOrigin(req: IncomingMessage): string | undefined {
  const host = firstForwarded(header(req, 'x-forwarded-host')) ?? header(req, 'host')
  if (host === undefined) return undefined
  const proto = firstForwarded(header(req, 'x-forwarded-proto'))
    ?? ((req.socket as IncomingMessage['socket'] & { encrypted?: boolean }).encrypted === true ? 'https' : 'http')
  try {
    return new URL(`${proto}://${host}`).origin
  } catch {
    return undefined
  }
}

function normalizeOrigin(raw: string): string | undefined {
  try {
    return new URL(raw).origin
  } catch {
    return undefined
  }
}

function localPeer(req: IncomingMessage): boolean {
  const remote = req.socket.remoteAddress
  return remote === '127.0.0.1' || remote === '::1' || remote === '::ffff:127.0.0.1'
}

/** Protect mutating routes while allowing the NAS app's loopback proxy. */
export function trustedRequest(req: IncomingMessage): boolean {
  const fetchSite = header(req, 'sec-fetch-site')?.trim().toLowerCase()
  if (fetchSite === 'cross-site') return false
  const origin = header(req, 'origin')
  if (origin !== undefined) return requestOrigin(req) === normalizeOrigin(origin)
  return localPeer(req)
}

function json(res: ServerResponse, status: number, value: unknown): void {
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-store',
    'x-content-type-options': 'nosniff',
  })
  res.end(JSON.stringify(value))
}

function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let body = ''
    let size = 0
    let finished = false
    req.setEncoding('utf8')
    req.on('data', (chunk: string) => {
      if (finished) return
      size += Buffer.byteLength(chunk)
      if (size > CODEX_SETTINGS_BODY_LIMIT) {
        finished = true
        reject(new Error('request body is too large'))
        return
      }
      body += chunk
    })
    req.on('end', () => {
      if (finished) return
      finished = true
      try {
        resolve(JSON.parse(body) as unknown)
      } catch {
        reject(new Error('request body is not valid JSON'))
      }
    })
    req.on('error', error => {
      if (finished) return
      finished = true
      reject(error)
    })
  })
}

function decodeSettingsWrite(value: unknown): CodexAuthSettingsConfig | undefined {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return undefined
  const record = value as Record<string, unknown>
  if (typeof record['enableImageTool'] !== 'boolean' || typeof record['enableImageUpload'] !== 'boolean') {
    return undefined
  }
  return decodeCodexAuthSettings(record)
}

/** Register the plugin-owned settings endpoint for browsers opened through a NAS authority. */
export function registerCodexSettingsRoute(
  ctx: Context,
  settings: SettingsScope<CodexAuthSettingsConfig>,
): void {
  ctx.effect(() => {
    const authorize = (req: IncomingMessage, res: ServerResponse): boolean => {
      if (trustedRequest(req)) return true
      json(res, 403, { error: REMOTE_WEB_ORIGIN_NOT_TRUSTED })
      return false
    }
    const dispose = ctx.webServer.register({
      kind: 'exact',
      path: CODEX_AUTH_SETTINGS_PATH,
      handler: async (req, res) => {
        if (req.method !== 'GET' && req.method !== 'PUT') return json(res, 405, { error: 'method not allowed' })
        if (!authorize(req, res)) return
        if (req.method === 'GET') return json(res, 200, settings.get())
        try {
          const next = decodeSettingsWrite(await readJsonBody(req))
          if (next === undefined) return json(res, 400, { error: CODEX_SETTINGS_INVALID })
          await settings.update(next)
          json(res, 200, settings.get())
        } catch (error: unknown) {
          json(res, 400, { error: safeMessage(error) })
        }
      },
    })
    return dispose
  }, 'dsh-codex-auth-plugin: remote settings route')
}

/** Register the auth endpoints when the DSH Web server is available. */
export function registerCodexAuthRoutes(
  ctx: Context,
  store: CodexCredentialStore,
  mirror?: CodexCredentialMirror,
): void {
  const auth = new CodexWebAuth(store, CODEX_AUTH_URL_TIMEOUT_MS, mirror)
  const usage = new CodexUsageService(store)
  ctx.effect(() => {
    const authorize = (req: IncomingMessage, res: ServerResponse): boolean => {
      if (trustedRequest(req)) return true
      json(res, 403, { error: REMOTE_WEB_ORIGIN_NOT_TRUSTED })
      return false
    }
    const routes = [
      ctx.webServer.register({
        kind: 'exact',
        path: CODEX_AUTH_STATUS_PATH,
        handler: async (req, res) => {
          if (req.method !== 'GET') return json(res, 405, { error: 'method not allowed' })
          if (!authorize(req, res)) return
          try {
            json(res, 200, await auth.status())
          } catch (error: unknown) {
            json(res, 500, { error: safeMessage(error) })
          }
        },
      }),
      ctx.webServer.register({
        kind: 'exact',
        path: CODEX_AUTH_LOGIN_PATH,
        handler: async (req, res) => {
          if (req.method !== 'POST') return json(res, 405, { error: 'method not allowed' })
          if (!authorize(req, res)) return
          try {
            json(res, 200, await auth.signIn())
          } catch (error: unknown) {
            json(res, 500, { error: safeMessage(error) })
          }
        },
      }),
      ctx.webServer.register({
        kind: 'exact',
        path: CODEX_AUTH_LOGOUT_PATH,
        handler: async (req, res) => {
          if (req.method !== 'POST') return json(res, 405, { error: 'method not allowed' })
          if (!authorize(req, res)) return
          try {
            await auth.signOut()
            json(res, 200, { ok: true })
          } catch (error: unknown) {
            json(res, 500, { error: safeMessage(error) })
          }
        },
      }),
      ctx.webServer.register({
        kind: 'exact',
        path: CODEX_USAGE_PATH,
        handler: async (req, res) => {
          if (req.method !== 'GET') return json(res, 405, { error: 'method not allowed' })
          if (!authorize(req, res)) return
          try {
            const value = await usage.read()
            if (value === undefined) return json(res, 401, { error: 'not-signed-in' })
            json(res, 200, value)
          } catch {
            json(res, 502, { error: CODEX_USAGE_UNAVAILABLE })
          }
        },
      }),
    ]
    return async () => {
      for (const dispose of routes) dispose()
      await auth.dispose()
    }
  }, 'dsh-codex-auth-plugin: Web OAuth routes')
}
