import type { ComponentItem, OutlineItem } from './types.ts'

/** 各组件页首屏的一句话描述。 */
export const componentDescriptions: Record<ComponentItem, string> = {
  'Button 按钮': '按钮用于开始一个即时操作，支持多种类型、主题、尺寸和交互状态。',
  'CodeBuddy 多账户': 'CodeBuddy 插件多用户管理的完整 UI 评定页：账号列表的多种运行状态，以及添加账号表单、危险操作确认与偏好设置表单。',
  'Cascader 级联选择': '级联选择用于从具有层级关系的选项中选择一个或多个值。',
  'TreeSelect 树选择器': '树选择器将树形结构与选择器结合，支持单选、多选和节点关系控制。',
  'Checkbox 复选框': '复选框用于在多个选项中进行选择，支持默认、选中、半选和禁用状态。',
  'Input 输入框': '输入框用于接收单行文本，支持清除、前后缀、校验状态、尺寸和禁用状态。',
  'InputNumber 数字输入框': '数字输入框用于输入和调整数值，支持步进、范围限制、精度和尺寸。',
  'Slider 滑块': '滑块用于在连续或离散区间内选择数值，支持单值、范围、刻度和提示。',
  'Switch 开关': '开关用于表示即时生效的二元状态，支持受控切换、文字和禁用状态。',
  'Form 表单': '表单用于组织字段、标签和提交操作，统一管理输入控件的布局与交互。',
  'Tree 树形控件': '树形控件用于展示具有层级关系的结构化数据，并支持展开、选中与复选。',
  'Collapse 折叠面板': '折叠面板用于将同类内容收纳进可展开的区域，适合账号列表、分组配置等纵向空间受限的场景。',
  'Icon 图标': '图标用于表达操作、状态和内容类型，统一从共享 Semi UI 包导出。',
  'Modal 对话框': '对话框用于承载需要用户确认或完成的任务，支持确认、取消和关闭交互。',
  'Tooltip 文字提示': '文字提示用于补充说明，不承载复杂交互，鼠标移入后延迟显示。',
  'Progress 进度条': '进度条用于展示操作的当前进度和状态，也可以表示任务或对象的完成度。',
  'Spin 加载器': '加载器用于告知用户内容正在加载，适用于时长不确定的异步操作。',
  'Toast 提示': 'Toast 用于对用户操作提供及时反馈，支持信息、成功、警告、错误和手动关闭。',
  'Popover 浮层': 'Popover 用于展示与当前操作相关的补充内容，支持点击触发和自定义内容。',
  'Dropdown 下拉框': '下拉菜单用于承载一组可点击的操作项，默认通过点击触发。',
  'Select 选择器': '选择器用于从一组选项中选择一个或多个值，支持多选、搜索、分组和校验状态。',
  'Skeleton 骨架屏': '骨架屏在内容加载完成前提供占位预期，支持头像、标题、段落、按钮和图片占位。',
  'Tabs 标签栏': '标签栏用于在同级内容之间快速切换，支持线条、卡片和按钮三种类型。',
  'Tag 标签': '标签用于标记、分类和轻量状态展示，支持颜色、尺寸、形状和可关闭。',
  'Avatar 头像': '头像用于展示用户或实体标识，支持字符、图标、图片、颜色、形状和头像组。',
  'Badge 徽标': '徽标出现在图标或文字右上角，用于展示需要关注的数据或状态。',
  'List 列表': '列表用于展示同类型结构化内容，支持头部尾部、边框、尺寸和空状态。',
  'Typography 排版': '排版组件统一管理标题、文本、段落和数值的展示、省略与复制。',
  'ScrollList 滚动列表': 'ScrollList 提供类似 iOS 的滚轮选择模式，也常作为自定义滚动容器。',
  'HotKeys 快捷键': 'HotKeys 为全局或指定区域注册快捷键组合，触发时执行响应动作。',
  'Layout 布局': '布局用于页面的整体结构划分，通过 Sider、Header、Content 和 Footer 组合。',
  'Nav 导航': '导航用于站点的层级组织与页面切换，支持垂直与水平布局。',
  'Table 表格': '表格用于展示结构化数据，支持行选择、分页与自定义渲染。',
  'Card 卡片': '卡片用于承载一组相关信息，支持标题、封面、内容与页脚区域。',
  'Descriptions 描述': '描述列表用于展示详情数据的只读键值对，支持多种布局。',
  'Empty 空状态': '空状态用于告知用户当前区域没有内容，并提供后续操作建议。',
}

/** 各组件页的右侧目录。 */
export const componentOutlines: Record<ComponentItem, OutlineItem[]> = {
  'Button 按钮': [['如何引入', 'how-to'], ['按钮类型', 'button-types'], ['按钮主题', 'button-theme'], ['状态', 'button-states'], ['组合与浮层', 'button-overlays']],
  'CodeBuddy 多账户': [['完整形态', 'cb-full'], ['多状态展示', 'cb-states'], ['添加账号表单', 'cb-form'], ['危险操作确认', 'cb-danger'], ['账号掉线与重新登录', 'cb-expired'], ['额度气泡', 'cb-usage'], ['偏好设置', 'cb-prefs']],
  'Cascader 级联选择': [['基本用法', 'selection-basic'], ['节点选中关系', 'selection-basic'], ['API 参考', 'selection-basic']],
  'TreeSelect 树选择器': [['基本用法', 'selection-basic'], ['节点选中关系', 'selection-basic'], ['API 参考', 'selection-basic']],
  'Checkbox 复选框': [['基本用法', 'checkbox-basic'], ['选中与半选', 'checkbox-states'], ['禁用状态', 'checkbox-disabled'], ['API 参考', 'checkbox-basic']],
  'Input 输入框': [['基本用法', 'input-basic'], ['尺寸与状态', 'input-states'], ['API 参考', 'input-basic']],
  'InputNumber 数字输入框': [['基本用法', 'input-number-basic'], ['范围与尺寸', 'input-number-states'], ['API 参考', 'input-number-basic']],
  'Slider 滑块': [['基本用法', 'slider-basic'], ['范围与刻度', 'slider-states'], ['API 参考', 'slider-basic']],
  'Switch 开关': [['基本用法', 'switch-basic'], ['文字与禁用', 'switch-states'], ['API 参考', 'switch-basic']],
  'Form 表单': [['基本用法', 'form-basic'], ['字段状态', 'form-states'], ['API 参考', 'form-basic']],
  'Tree 树形控件': [['基本用法', 'tree-basic'], ['复选与半选', 'tree-basic'], ['选中与禁用', 'tree-basic'], ['API 参考', 'tree-basic']],
  'Collapse 折叠面板': [['基本用法', 'collapse-basic'], ['多用户管理示例', 'collapse-users'], ['创建用户', 'collapse-create']],
  'Icon 图标': [['图标列表', 'tree-icons'], ['基础使用', 'tree-icons-basic'], ['尺寸与状态', 'tree-icons-states'], ['颜色与双色图标', 'tree-icons-colors'], ['API 参考', 'tree-icons']],
  'Modal 对话框': [['基本用法', 'modal-basic'], ['按钮与内容状态', 'modal-states'], ['信息反馈状态', 'modal-methods'], ['API 参考', 'modal-basic']],
  'Progress 进度条': [['标准进度条', 'progress-basic'], ['圆形进度条', 'progress-circle'], ['自定义文本', 'progress-format']],
  'Spin 加载器': [['基本用法', 'spin-basic'], ['尺寸', 'spin-size'], ['包裹内容', 'spin-content']],
  'Toast 提示': [['普通提示', 'toast-basic'], ['状态提示', 'toast-status'], ['手动关闭与堆叠', 'toast-control']],
  'Popover 浮层': [['基本用法', 'popover-basic'], ['箭头与位置', 'popover-basic'], ['API 参考', 'popover-basic']],
  'Dropdown 下拉框': [['基本用法', 'dropdown-basic'], ['嵌套使用', 'dropdown-nested'], ['弹出位置', 'dropdown-position'], ['触发方式', 'dropdown-trigger'], ['触发事件', 'dropdown-events'], ['JSON 用法', 'dropdown-json'], ['API 参考', 'dropdown-api']],
  'Tooltip 文字提示': [['基本用法', 'tooltip-basic'], ['API 参考', 'tooltip-basic']],
  'Select 选择器': [['基本用法', 'select-basic'], ['多选与标签', 'select-multiple'], ['尺寸与状态', 'select-states'], ['API 参考', 'select-basic']],
  'Skeleton 骨架屏': [['基本用法', 'skeleton-basic'], ['组合占位', 'skeleton-combo'], ['加载切换', 'skeleton-toggle']],
  'Tabs 标签栏': [['基本用法', 'tabs-basic'], ['类型与禁用', 'tabs-states'], ['滑动与溢出', 'tabs-states']],
  'Tag 标签': [['基本用法', 'tag-basic'], ['颜色与形状', 'tag-colors'], ['可关闭标签', 'tag-closable']],
  'Avatar 头像': [['基本用法', 'avatar-basic'], ['颜色与形状', 'avatar-colors'], ['头像组', 'avatar-group']],
  'Badge 徽标': [['基本用法', 'badge-basic'], ['溢出与位置', 'badge-states'], ['独立使用', 'badge-states']],
  'List 列表': [['基本用法', 'list-basic'], ['模板用法', 'list-template'], ['尺寸与空状态', 'list-states']],
  'Typography 排版': [['标题组件', 'typography-title'], ['文本组件', 'typography-text'], ['段落与数值', 'typography-paragraph'], ['省略与复制', 'typography-ellipsis']],
  'ScrollList 滚动列表': [['基本用法', 'scrolllist-basic'], ['自定义滚动容器', 'scrolllist-container']],
  'HotKeys 快捷键': [['基本用法', 'hotkeys-basic'], ['阻止默认事件', 'hotkeys-prevent']],
  'Layout 布局': [['基本用法', 'layout-basic'], ['侧边布局', 'layout-basic'], ['API 参考', 'layout-basic']],
  'Nav 导航': [['基本用法', 'nav-basic'], ['受控选中', 'nav-states'], ['API 参考', 'nav-basic']],
  'Table 表格': [['基本表格', 'table-basic'], ['行选择', 'table-basic'], ['API 参考', 'table-basic']],
  'Card 卡片': [['基本用法', 'card-basic'], ['阴影与边线', 'card-states'], ['API 参考', 'card-basic']],
  'Descriptions 描述': [['基本用法', 'descriptions-basic'], ['布局与尺寸', 'descriptions-states'], ['API 参考', 'descriptions-basic']],
  'Empty 空状态': [['基本用法', 'empty-basic'], ['自定义内容', 'empty-states'], ['API 参考', 'empty-basic']],
}
