import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

describe('dsh-codex-auth-plugin rc.2 client registration', () => {
  it('uses the required key for the keyed settings plugin slot', async () => {
    const client = await readFile(new URL('../src/client/index.tsx', import.meta.url), 'utf8')
    expect(client).toContain("ctx.slots.inject('settings.plugin.item'")
    expect(client).toContain("name: 'settings.plugin.item'")
    expect(client).toContain('key: CODEX_AUTH_SETTINGS_NAMESPACE')
    expect(client).toContain("'connection', 'remote', 'settingsScope'")
    expect(client).toContain('decodeCodexAuthSettings')
    expect(client).toContain('configScope')
    expect(client).toContain('installCodexModelEditorPresentation')
    expect(client).toContain("from '@tnnevol/dsh-semi-ui'")
    expect(client).toContain("installSemiDshTheme(), 'dsh-codex-auth-plugin: Semi DSH theme'")
    expect(client).not.toContain('id: \'dsh-codex-auth-plugin\'')
  })

  it('adds the Codex-only model picker enhancements without changing the official source', async () => {
    const presentation = await readFile(new URL('../src/client/model-editor-presentation.ts', import.meta.url), 'utf8')
    expect(presentation).toContain('选择要添加的模型')
    expect(presentation).toContain('全选')
    expect(presentation).toContain("const replacement = chinese ? '确定' : 'Confirm'")
    expect(presentation).toContain('--dsw-alias-button-primary-fill')
    expect(presentation).toContain('CODEX_EDITOR_ATTRIBUTE')
    expect(presentation).toContain('REMOVE_MANUAL_ADD_ATTRIBUTE')
    expect(presentation).toContain('添加模型')
    expect(presentation).toContain('PICKER_SELECTION_SYNCED_ATTRIBUTE')
    expect(presentation).toContain('MODEL_ACTION_ATTRIBUTE')
    expect(presentation).toContain('MODEL_DETAILS_ATTRIBUTE')
    expect(presentation).toContain('details.open = true')
    expect(presentation).toContain('display: contents')
    expect(presentation).toContain('section[aria-label="模型目录"]')
    expect(presentation).toContain('获取模型')
    expect(presentation).toContain('恢复模型')
    expect(presentation).toContain('if (button.textContent !== action.replacement)')
    expect(presentation).toContain('gap: 15px')
    expect(presentation).toContain('margin-left: auto')
    expect(presentation).toContain('模型列表')
    expect(presentation).toContain('uncheckedModelRows')
    expect(presentation).toContain('removeUncheckedModelRows')
    expect(presentation).toContain('pickerConfirmReplay')
    expect(presentation).toContain('删除模型')
    expect(presentation).toContain('Delete model')
    expect(presentation).toContain('Select the models to keep')
    expect(presentation).toContain('background: var(--dsw-alias-bg-layer-1)')
    expect(presentation).toContain('模型 ID')
    expect(presentation).toContain('MODEL_READONLY_LABELS')
    expect(presentation).toContain('MODEL_NAME_LABELS')
    expect(presentation).toContain('`[${CODEX_EDITOR_ATTRIBUTE}="true"]`')
    expect(presentation).toContain('input.readOnly = true')
    expect(presentation).toContain("setAttribute('aria-readonly', 'true')")
    expect(presentation).toContain('128_000')
    expect(presentation).toContain('272_000')
    expect(presentation).toContain('accent-color: var(--dsw-alias-button-primary-fill)')
    expect(presentation).toContain('var(--dsw-alias-border-l4)')
  })

  it('renders the weekly quota as remaining usage', async () => {
    const card = await readFile(new URL('../src/client/CodexAuthCard.tsx', import.meta.url), 'utf8')
    expect(card).toContain('remainingPercent')
    expect(card).toContain("t('usageWeekly')")
    expect(card).toContain("t('usageRemaining')")
    expect(card).not.toContain('value.usedPercent')
  })

  it('opens the global model cascade on parent hover and keeps it open after leaf clicks', async () => {
    const picker = await readFile(new URL('../src/client/CodexGlobalModel.tsx', import.meta.url), 'utf8')
    expect(picker).toContain("import { DshButton } from '@tnnevol/dsh-semi-ui'")
    expect(picker).toContain('<DshButton htmlType="button"')
    expect(picker).toContain('onClick={onToggle}')
    expect(picker).toContain("onHover={() => { openSubmenu('model') }}")
    expect(picker).toContain("onHover={() => { openSubmenu('effort') }}")
    expect(picker).toContain('const openSubmenu = (menu: ChoiceMenuKind): void =>')
    expect(picker).toContain('onLeave={closeSubmenuOnParentLeave}')
    expect(picker).toContain("target.closest('[data-dsh-cascade-submenu]')")
    expect(picker).toContain('scheduleSubmenuClose')
    expect(picker).toContain('onMouseEnter={cancelScheduledClose}')
    expect(picker).toContain('onClick={() => { onChooseModel(option.id) }}')
    expect(picker).toContain('onClick={() => { onChooseEffort(option.id) }}')
    expect(picker).toContain('onMouseLeave={onCloseSubmenu}')
    expect(picker).toContain('var(--dsw-alias-interactive-bg-hover, var(--dsw-alias-bg-layer-1))')
    expect(picker).not.toContain('onMouseEnter={() => { onChooseModel(option.id) }}')
    expect(picker).not.toContain('onMouseEnter={() => { onChooseEffort(option.id) }}')
    expect(picker).toContain("onChooseModel={id => { setDraftModel(id); setDraftEffort(''); setFeedback('idle') }}")
    expect(picker).toContain("onChooseEffort={id => { setDraftEffort(id); setFeedback('idle') }}")
    expect(picker).toContain("onCloseSubmenu={() => { setOpenMenu('root') }}")
  })

  it('matches the DSH plugin card surfaces in both color modes', async () => {
    const card = await readFile(new URL('../src/client/CodexAuthCard.tsx', import.meta.url), 'utf8')
    expect(card).toContain('var(--dsw-alias-bg-layer-3)')
    expect(card).toContain('var(--dsw-alias-bg-layer-2)')
    expect(card).toContain('borderRadius: 12')
    expect(card).toContain("padding: '14px 16px'")
  })

  it('exposes image upload alongside image recognition', async () => {
    const capabilities = await readFile(new URL('../src/client/CodexCapabilities.tsx', import.meta.url), 'utf8')
    const locales = await readFile(new URL('../src/client/locales.ts', import.meta.url), 'utf8')
    expect(capabilities).toContain('enableImageUpload')
    expect(capabilities).toContain('updateImageUpload')
    expect(capabilities).toContain("t('enableImageUpload')")
    expect(locales).toContain('启用图片上传')
  })
})
